[package]
name = "fariba-ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
strfmt = "0.2.4"
serde_json = "1.0.120"

tokio = { version = "1.39.2", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["json", "rustls-tls"] }
